import React from 'react'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css';
import '../styles/globals.css'
import Layout from '../components/layout'
import Head from 'next/head'
import store from '../store'
import { AlertModal } from '../components/alertModal'
import { Provider } from 'react-redux'

function MyApp({ Component, pageProps }) {
  return (
		<Provider store={store}>
			<Head>
				<title>Accounting CMS</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Layout>
				<AlertModal />
				<Component {...pageProps} />
			</Layout>
		</Provider>
	)
}

export default MyApp
