version: '3.8'
services:
  cms_db:
    hostname: cms_db
    container_name: cms_db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - local.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes: 
      - cms_db:/var/lib/postgresql/data
volumes:
  cms_db:
    driver: local
